### ISSUE TITLE
Taiwaness Moe Dict support

### ISSUE THREAD

**Issue by iblis17** [zdict/zdict#108]
e.g. https://www.moedict.tw/'%E6%9C%A8%E8%80%B3

**Comment by iblis17** [comment]
http://itaigi.tw/ another Taiwaness Dict

**Comment by wdv4758h** [comment]
As we already have support for Moe Dict's Traditional Chinese, we can support Moe Dict's Taiwanese in two ways:

* additional arguments for `zdict --dict moe` to choose Taiwanese
* another `MoeDictTaiwanese` class and use it by `zdict --dict moe-taiwanese`

I'll vote for additional arguments in this case.

**Need more comments !**

**Comment by M157q** [comment]
+1 for the former.

**Comment by pi314** [comment]
+1 for moe-taiwanese

**Comment by M157q** [comment]
uh... now we have a 2v2 situation.

The reason why I supports additional arguments for a dictionary instead of creating a new dictionary is that, if we have other dictionaries with same situation and we deal it with creating a new dictionary, we may come up with too many dictionaries in the `-d` command line arguments. Thus, I think adding an option for selecting an available language for a dictionary is better.

**Comment by wdv4758h** [comment]
Added in #114
