### ISSUE TITLE
import error on Windows, no "HOME" environment variable

### ISSUE THREAD

**Issue by bnn00023** [zdict/zdict#148]
Hi zdict：
    I feel this is good stuff,I want use it.First I install it.And I use my Python3.6 import zdict,that issue error.
My operating is wrong? Sorry my English is not well.

```
Traceback (most recent call last):
  File "D:/Algorithm/test.py", line 1, in <module>
    import zdict.zdict
  File "C:\Users\E17012\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zdict\__init__.py", line 1, in <module>
    from zdict import utils
  File "C:\Users\E17012\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zdict\utils.py", line 4, in <module>
    from zdict import constants
  File "C:\Users\E17012\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zdict\constants.py", line 7, in <module>
    BASE_DIR = os.path.join(os.getenv('HOME'), BASE_DIR_NAME)
  File "C:\Users\E17012\AppData\Local\Programs\Python\Python36-32\lib\ntpath.py", line 75, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by M157q** [comment]
@bnn00023  `os.getenv('HOME')` return `None` caused this error.

I think it's because you are using Windows and we don't have any testings for Windows platform. Honestly, this is a side project and none of developers of this project using zdict in Windows. [See these two lines in `setup.py`? No Windows.](https://github.com/zdict/zdict/blob/master/setup.py#L99-L100)

But, we will be glad to see zdict work on Windows, so I will try to fix this bug. Yet, I don't think will zdict work on Windows just after I solve this bug. (If it does, it would be great. Just let you know first.) 

If would be great if you can help us test zdict on Windows platform. =)

**Comment by bnn00023** [comment]
Thank your answer,and my platform is windows 7. If need my test on W7 or W10,it is my pleasure.

**Comment by M157q** [comment]
@bnn00023 I'm wondering if you can use `zdict` with `docker` on Windows 7 or Windows 10. Could you give it a try?

**Comment by bnn00023** [comment]
Yes I can. But... I never use docker. I will learn it. Give my some time.

**Comment by bnn00023** [comment]
this is on Windows 7


> E17012@prodser MINGW64 ~
> $ zdict
> Traceback (most recent call last):
>   File "C:/Users/E17012/AppData/Local/Programs/Python/Python36-32/Scripts/zdict"
> , line 3, in <module>
>     from zdict import zdict
>   File "C:\users\e17012\appdata\local\programs\python\python36-32\lib\site-packa
> ges\zdict\__init__.py", line 1, in <module>
>     from zdict import utils
>   File "C:\users\e17012\appdata\local\programs\python\python36-32\lib\site-packa
> ges\zdict\utils.py", line 99, in <module>
>     readline = import_readline()
>   File "C:\users\e17012\appdata\local\programs\python\python36-32\lib\site-packa
> ges\zdict\utils.py", line 95, in import_readline
>     import readline
> ModuleNotFoundError: No module named 'readline'



I try search "readline" want know what's happen , but I lost it...

I don't know my operating is right or wrong. if it's wrong .Please tell me.

**Comment by wdv4758h** [comment]
I don't think CPython has builtin readline support on Windows.

There is a pure Python implementation called [pyreadline](https://github.com/pyreadline/pyreadline) for Windows, but it isn't updated for 2 years. The **pyreadline** was developed by IPython community as gnureadline replacement for Windows, but they removed both pyreadline and gnureadline dependencies in favor of [prompt-toolkit](https://github.com/jonathanslenders/python-prompt-toolkit) now.

**Comment by wdv4758h** [comment]
Actually, I have a opening issue for [prompt-toolkit support](https://github.com/zdict/zdict/issues/60), but I've never spent time on it :P

**Comment by wdv4758h** [comment]
We probably are able to run on the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about) though, but I don't have any enviroment to test.

**Comment by bnn00023** [comment]
@wdv4758h 
Hi,wdv4758h
I install  `prompt-toolkit support` and import it. It show error message. And I see 

> Runs on all Python versions from 2.6 up to 3.5. 

In Python Prompt Toolkit\README.rst.

Should I use Python 3.5？

**Comment by wdv4758h** [comment]
I think `prompt-toolkit` works fine on CPython 3.6, since I'm using version 3.6 :P 

But the problem is `zdict` does not support `prompt-toolkit` yet, so it's not a drop-in replacement here.

Let me summarize them:

* `zdict` use `readline` or `gnureadline`, but Windows doesn't have any of them
* there is a `pyreadline` **probably** can easily fix the problem with very few modification in `zdict`
* `zdict` probably can work on the `Windows Subsystem for Linux`
* there is a way can remove `readline`/`gnureadline` dependencies, which is use `prompt-toolkit` for our interactive shell, but it needs more modification in `zdict`

**Comment by bnn00023** [comment]
No module named 'readline' ← The error miss when I install `pyreadline` after.Now happen new problem.

![image](https://user-images.githubusercontent.com/15090505/34028584-122ab8aa-e19f-11e7-9edf-65d32752c560.png)

I use docker toolbox with Windows 7.

**Comment by bnn00023** [comment]
I can use this！！
![image](https://user-images.githubusercontent.com/15090505/34096816-b651416e-e411-11e7-8296-b2c64fa6c11e.png)
but... I don't remember what step when I do. maybe useful step is install  `pyreadline`.

this is docker toolbox with Windows 7. I will test on Windows 10 next time.

**Comment by M157q** [comment]
The problem in [this comment](https://github.com/zdict/zdict/issues/148#issuecomment-351920528) is:

You did it wrong when you typed `export LC_ALL=UTF-8` and `export LANG=UTF-8`.
You ignored the warning in the first line. It told you there's no locale named `UTF-8`.
You can use `locale -a` to see what encodings you can set.

You can use `locale` to see your current locale-specific info.
I believe it's something like `en_US.UTF-8` or `zh_TW.UTF-8`.

**Comment by bnn00023** [comment]
it's successful on Windows 10 with docker toolbox. I will check what happen on Windows 7. Maybe my procedures is wrong.
![image](https://user-images.githubusercontent.com/15090505/34113035-627fe418-e449-11e7-9521-71b7b2dceec0.png)
